Repository edgexfoundry/cd-management, pull requests merged in 2020-10, with the labels that each got.

#79 init: Add new files to seed a Jenkins server
  README.md
  create.sh
  edgexfoundry-folder.xml
  edgexfoundry-org.xml
Labels: enhancement, good first issue, hanoi

#83 Fix intermittent ratelimit error
  Jenkinsfile
  README.md
  build.py
  requirements.txt
  src/main/python/githubsync/api.py
  src/unittest/python/test_api.py
Labels: bug, hanoi

#85 Refactor to leverage github3api module - prune-github-tags
  Dockerfile
  Dockerfile.build
  Jenkinsfile
  README.md
  build.py
  docs/images/screen.gif
  requirements.txt
  src/main/python/prunetags/__init__.py
  src/main/python/prunetags/api.py
  src/main/python/prunetags/cli.py
  src/unittest/python/test_api.py
  src/unittest/python/test_cli.py
Labels: tech-debt

#86 Refactor to leverage github3api module - create-github-release
  Dockerfile
  Jenkinsfile
  README.md
  build.py
  requirements.txt
  src/main/python/cr8rel/__init__.py
  src/main/python/cr8rel/api.py
  src/main/python/cr8rel/cli.py
  src/unittest/python/test_api.py
  src/unittest/python/test_cli.py
Labels: tech-debt

#89 run docker-bench-security checks against EdgeX stack
  Jenkinsfile
Labels: 1-low, enhancement
