Repository edgexfoundry/cd-management, pull requests merged in 2020-07, with the labels that each got.

#51 Fix error due to upstream restclient change
  build.py
  src/main/python/githubsync/api.py
  src/unittest/python/test_api.py
Labels: bug, hanoi

#56 Implement prune-github-tags capability
  .gitignore
  Dockerfile
  Dockerfile.build
  Jenkinsfile
  README.md
  build.py
  reports/edgexfoundry-07.09.2020-22.02.05.csv
  reports/edgexfoundry-07.14.2020-17.05.59.json
  requirements-build.txt
  requirements.txt
  src/main/python/prunetags/__init__.py
  src/main/python/prunetags/api.py
  src/main/python/prunetags/cli.py
  src/unittest/python/test_api.py
  src/unittest/python/test_cli.py
Labels: enhancement, hanoi

#59 feat: Add code to simplify exporting dockerhub data for edgexfoundry.
  .gitignore
  Dockerfile
  Jenkinsfile
  README.md
  build.py
  requirements-build.txt
  requirements.txt
  src/main/python/dha/__init__.py
  src/main/python/dha/cli.py
  src/unittest/python/test_cli.py
Labels: 1-low, hanoi

#61 feat: pull VERSION from git-semver
  Jenkinsfile
Labels: 2-medium, hanoi
