Repository edgexfoundry/cd-management, pull requests merged in 2020-06, with the labels that each got.

#26 Refactor to Python script
  .coveragerc
  .gitignore
  Dockerfile
  Jenkinsfile
  README.md
  build.py
  requirements-build.txt
  requirements.txt
  src/main/python/githubsync/__init__.py
  src/main/python/githubsync/api.py
  src/main/python/githubsync/cli.py
  src/unittest/python/test_api.py
  src/unittest/python/test_cli.py
Labels: enhancement, hanoi

#35 release(geneva dot): Release Device C SDK (v1.2.1)
  release/device-sdk-c.yaml
Labels: geneva

#36 Fix issue with sync milestones
  build.py
  src/main/python/githubsync/api.py
  src/main/python/githubsync/cli.py
  src/unittest/python/test_api.py
  src/unittest/python/test_cli.py
Labels: bug, hanoi

#45 release(geneva dot): Re-push Docker Images to DockerHub and Nexus
  release/app-service-configurable.yaml
  release/device-camera-go.yaml
  release/device-modbus-go.yaml
  release/device-mqtt-go.yaml
  release/device-random.yaml
  release/device-rest-go.yaml
  release/device-snmp-go.yaml
  release/device-virtual-go.yaml
  release/edgex-go.yaml
Labels: geneva

#44 release(geneva dot): Release EdgeX Snaps to stable channels
  release/app-service-configurable.yaml
  release/device-modbus-go.yaml
  release/device-mqtt-go.yaml
  release/edgex-go.yaml
Labels: geneva

#47 release(geneva): Release Device Grove C service (1.2.0) and Testing frameworks (1.2.1)
  release/blackbox-testing.yaml
  release/device-grove-c.yaml
  release/edgex-taf.yaml
Labels: geneva
