Repository edgexfoundry/cd-management, pull requests merged in 2020-04, with the labels that each got.

#7 Add jenkinsfile for edgex-go-snap-daily build job.
  Jenkinsfile
  README.md
Labels: 2-medium, enhancement

#6 Functional Testing - update endpoints to test release
  Jenkinsfile
  release/sample-service.yaml
Labels: 2-medium, geneva

#12 geneva: Release Device Go SDK
  release/device-sdk-go.yaml
  release/sample-service.yaml
Labels: geneva
