Repository edgexfoundry/cd-management, pull requests merged in 2021-04, with the labels that each got.

#137 chore(ci): trigger the docker CIS scan on a weekly basis
  Jenkinsfile
Labels: ci

#141 ci: update to use edgex-compose repo rather than developer-scripts
  Jenkinsfile
Labels: 2-medium, ci

#146 docs: Add badges to readme
  README.md
Labels: documentation
